package com.simats.personalisednutritionapp

sealed class Screen(val route: String) {
    object Welcome : Screen("welcome")
    object SignUp : Screen("signup")
    object Login : Screen("login")
    object AgeGender : Screen("age_gender")
    object HeightWeight : Screen("height_weight")
    object Goal : Screen("goal")
    object HealthConditions : Screen("health_conditions")
    object HealthDetails : Screen("health_details")
    object MealsPerDay : Screen("meals_per_day")
    object DietaryPreferences : Screen("dietary_preferences")
    object CuisinePreferences : Screen("cuisine_preferences")
    object Home : Screen("home")
    object FoodPreferences : Screen("food_preferences")
    object LifestyleAndActivity : Screen("lifestyle_and_activity")
    object GoalWeight : Screen("goal_weight")
    object WaterTracking : Screen("water_tracking")
    object StepsTracking : Screen("steps_tracking")
    object LogFood : Screen("log_food")
    object AiTips : Screen("ai_tips")
    object ManualFoodEntry : Screen("manual_food_entry")
    object ScanFood : Screen("scan_food")
    object Register : Screen("register")
    object Splash : Screen("splash")
    object Onboarding1 : Screen("onboarding1")
    object Onboarding2 : Screen("onboarding2")
    object Onboarding3 : Screen("onboarding3")
    object ForgotPassword : Screen("forgot_password")
    object PersonalDetails : Screen("personal_details")
    object BodyDetails : Screen("body_details")
    object Goals : Screen("goals")
    object MealPlan : Screen("meal_plan")
    object History : Screen("history")
    object StressAndSleep : Screen("stress_and_sleep")
    object Recipes : Screen("recipes")
    object Insights : Screen("insights")
    object Settings : Screen("settings")
}
